### ISSUE TITLE
Also import related issues

### ISSUE THREAD

**Issue by voorproever** [fusonic/redmine-import#1]
[Gitlab.com](https://gitlab.com/) is now running GitLab 9.4.0RC2: [https://twitter.com/gitlabstatus/status/885627837704785920](https://twitter.com/gitlabstatus/status/885627837704785920) and therefore now supports issue links.

Support should be added to the `ImportCommand`.

API docs: [https://docs.gitlab.com/ee/api/issue_links.html](https://docs.gitlab.com/ee/api/issue_links.html)

**Comment by mburtscher** [comment]
@voorproever Could be implemented now.
